language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t feedapi udagram-feed_api
  - docker build -t frontend udagram-frontend
  - docker build -t userapi udagram-user_api
  - docker build -t reverseproxy Reverseproxy
  
  - docker tag feedapi maxha89/feedapi:latest
  - docker tag frontend maxha89/frontend:latest
  - docker tag userapi maxha89/userapi:latest
  - docker tag reverseproxy maxha89/reverseproxy:latest  #Image noch erstellen
  

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push maxha89/feedapi
  - docker push maxha89/frontend
  - docker push maxha89/userapi
  - docker push max89/reverseproxy
